### ISSUE TITLE
Unity ARFoundation's Face tracking support

### ISSUE THREAD

**Issue by lincode** [AgoraIO/Video-Call-for-Mobile-Gaming#12]
The video RTC feature works well. But it couldn't work with Unity ARFoundation's Face tracking.

I'm working on a video chat feature with ARFoundation like Facetime with Animoji or Memoji in iOS. But when I setup EnableVideo() and EnableVideoObserver(), I find that the face tracking updating is stopped.

**Comment by zhangtao1104** [comment]
Please download the sdk from this link: 

https://apprtcio-my.sharepoint.com/:u:/g/personal/zhangtao_agora_io/ESYzUKCKs55Or7_mCcfkeZABeah9akm92hIeIrttTjloZQ


The sdk in the top can support ARFoundation, you can use this sdk according to the link :

https://github.com/AgoraIO/Video-Call-for-Mobile-Gaming/issues/9

**Comment by jakep84** [comment]
Is this functionality available in the latest version I have to push to the unity asset store? Several developers are asking for this functionality.

**Comment by zhangtao1104** [comment]
Yes, it support this.

**Comment by jakep84** [comment]
Awesome! Thanks!

**Comment by lincode** [comment]
@jakep84 You will upload this version recently? I prefer to use the package downloaded from asset store.

**Comment by zhangtao1104** [comment]
Yes, we will upload this version recently, if you prefer to use the sdk downloaded from the unity asset store, please wait a few days. @lincode

**Comment by JameelQureshi** [comment]
Hello Can you please send any sample project or tutorial so i can use ARFoundation with agora
currently i can't find anything

**Comment by lincode** [comment]
Agree. If there is any sample project, that will be very helpful.

**Comment by zhangtao1104** [comment]
Ok, we are glad to hear your suggestions @JameelQureshi  @lincode  and we will plan to do this work.

**Comment by zhangtao1104** [comment]
I had communicated with our product manager about this feature, if there is any progress ,i will tell you.

**Comment by lincode** [comment]
@zhangtao1104 Thanks for your work. By the way, I haven't yet worked out the ARFoundation with the new Agora SDK (2.9.0.2). At least in my case, it doesn't work.

**Comment by pablopalma** [comment]
There's some example to integrate the AR Foundation Face Tracking with Agora IO?

**Comment by zhangtao1104** [comment]
@icywind  Please help to provide the Unity AR Demo link.

**Comment by pablopalma** [comment]
@zhangtao1104 i solved it, thanks anyway. Then i will do some tutorial about this case.
