### ISSUE TITLE
Metal Support in iOS Device

### ISSUE THREAD

**Issue by lincode** [AgoraIO/Video-Call-for-Mobile-Gaming#13]
According to the doc https://docs.agora.io/en/Interactive%20Gaming/game_unity_ios_video?platform=Unity_(iOS), It only supports openGLSE2 graphics API. Do you have any plan to support Metal in iOS?

**Comment by zhangtao1104** [comment]
In fact, if you download the sdk in the unity asset store, the sdk support any render.
