### ISSUE TITLE
It misses audio recording with ReplayKit in iOS

### ISSUE THREAD

**Issue by lincode** [AgoraIO/Video-Call-for-Mobile-Gaming#14]
I couldn't recording audio with ReplayKit in iOS. From I load the agora engine, the output video of ReplayKit start to be mute without any sound.

**Comment by zhangtao1104** [comment]
mRtcEngine.SetParameters("{\"che.audio.keep.audiosession\":true}");
mRtcEngine.SetParameters(“{\"che.audio.mixable.option\": true};
You can call this two api before joinChannel and try again.

**Comment by lincode** [comment]
@zhangtao1104 Thanks for your suggestion. I tried. It didn't work as before.

**Comment by anovoselskyi** [comment]
Also doesn't work. I'm trying to record screen during the video call, but the audio doesn't record

**Comment by zhangtao1104** [comment]
You want to make a real time video communication, at the same time you want to capture the screen and record the audio of the speaker by replaykit. But the result is that you can not record the audio of the speaker right? @anovoselskyi

**Comment by anovoselskyi** [comment]
@zhangtao1104 yes, it's correct. I would like to have a record live video call with audio from the speaker and microphone using ReplayKit.

**Comment by zhangtao1104** [comment]
You can try to call api named SetAudioProfile(AUDIO_PROFILE_TYPE.AUDIO_PROFILE_DEFAULT,  AUDIO_SCENARIO_TYPE.AUDIO_SCENARIO_GAME_STREAMING)  before you call joinChannel.

Please have a try.

**Comment by anovoselskyi** [comment]
@zhangtao1104 it's fixing my issue. Thank you so much 🎉
