### ISSUE TITLE
Issues when using ARFoundation and Unity 2019.3.0f3 in your default scene

### ISSUE THREAD

**Issue by yosun** [AgoraIO/Video-Call-for-Mobile-Gaming#21]
Plugin 'agora_rtc_sdk.dll' is used from several locations:
 Assets/Plugins/x86/agora_rtc_sdk.dll would be copied to <PluginPath>/agora_rtc_sdk.dll
 Assets/Plugins/x86_64/agora_rtc_sdk.dll would be copied to <PluginPath>/agora_rtc_sdk.dll
Plugin 'agoraSdkCWrapper.dll' is used from several locations:
 Assets/Plugins/x86_64/agoraSdkCWrapper.dll would be copied to <PluginPath>/agoraSdkCWrapper.dll
 Assets/Plugins/x86/agoraSdkCWrapper.dll would be copied to <PluginPath>/agoraSdkCWrapper.dll
Please fix plugin settings and try again.

**Comment by icywind** [comment]
You may want to clean your Unity plugin cache first before import the SDK.

**Comment by yosun** [comment]
Actually this is just from opening the sample project from your website
-- 
Yosun Chang, Founder and CTO

I'm apparently the only solo woman AR creator interviewed on the SIGGRAPH
blog:
https://blog.siggraph
.org/2019/01/with-mobile-ar-you-can-graffiti-on-the-mona-lisa.html/

Phone: (415) 779 6786
WWW: AReality3D.com
Twitter: @yosun

**Comment by icywind** [comment]
I see what could be your issue.  Did you take a look at the README file? Anyways, make sure you change the properties of the associated files.  Here is a screenshot of a sample. In this sample, the win 32bit libraries is enabled, see highlighted area.  If you enabled 32bit (from x86 folder)then you should turn off those for the x86_64 files.
<img width="1145" alt="importSettings" src="https://user-images.githubusercontent.com/1261195/84458603-47166a80-ac1a-11ea-91b2-0228918ecf51.png">

**Comment by yosun** [comment]
Still experiencing issues - can you let me know which Unity you are using. Also, do you support Unity 2019.3?

**Comment by zhangtao1104** [comment]
Yes, we support 2019.3. Do you still have this issues? 
If you still have this issure, please provide a screenshot and the full log.
Maybe you can clean the cache or download it and open it as a new project.
