### ISSUE TITLE
Video Call Taking a long Time To satrt

### ISSUE THREAD

**Issue by Qusai-Tech** [AgoraIO/Video-Call-for-Mobile-Gaming#29]
hello guys, 
I downloaded the SD and setup the project and added the AppID.

it is taking like 5 minutes to render the video, and whenever other user joins the same channel 
it will not appear ?

thank in advance for the help

**Comment by icywind** [comment]
Hi, can you come to chat with me at [Unity-Help-Me Slack channel ](https://agoraiodev.slack.com/archives/CFDG7Q6F6)
so we can communicate more efficiently.
-Rick
