### ISSUE TITLE
Connected but not seeing video. 

### ISSUE THREAD

**Issue by jumbohiggins** [AgoraIO/Video-Call-for-Mobile-Gaming#7]
Hello, I have set up the Unity SDK on two android phones and can join the same channel. When the second phone joins the channel a large black box appears on both phones but no video is transmitted.

**Comment by zhangtao1104** [comment]
what is unity version?

**Comment by zhangtao1104** [comment]
what is your unity version?

**Comment by jumbohiggins** [comment]
2018.3.6f1

**Comment by zhangtao1104** [comment]
Please use "git pull" to update the demo source code and try again

**Comment by jumbohiggins** [comment]
Well now the black 2d plane is gone but still no video or anything. 

Now it just loads the hello scene with a white cylinder and cube.

**Comment by zhangtao1104** [comment]
you need to add the VideoSurface.cs to the cube or the cylinder which you want to render the video.

**Comment by jumbohiggins** [comment]
I did

**Comment by zhangtao1104** [comment]
[Hello-Video-Unity-Agora.zip](https://github.com/AgoraIO/Video-Call-for-Mobile-Gaming/files/3043144/Hello-Video-Unity-Agora.zip)

**Comment by zhangtao1104** [comment]
Please try the demo which i upload, I only put android plugin into it, if you want to run the demo in iphone, please put the ios plugin into it.

**Comment by zhangtao1104** [comment]
If you want to run android only , you just need to sign up a project int this link https://sso.agora.io/en/signup   , and get the appId . Then  Fill in the appId in the demo(HelloUnityVideo.cs). At last, build it and run in the android phone

**Comment by jumbohiggins** [comment]
Thanks Zhang the video is coming across now.
