### ISSUE TITLE
Does it work for windows?

### ISSUE THREAD

**Issue by cosmo-naut** [AgoraIO/Video-Call-for-Mobile-Gaming#8]
I want to add Agora to a Windows Unity project, not mobile. Will it work?

**Comment by zhangtao1104** [comment]
[AMG_FULL_Win_Unity_4_4.zip](https://github.com/AgoraIO/Video-Call-for-Mobile-Gaming/files/3170016/AMG_FULL_Win_Unity_4_4.zip)

**Comment by zhangtao1104** [comment]
If you want to add agora to a win project, you need to use the unity win plugin in the attachment.

**Comment by cosmo-naut** [comment]
Thank you

**Comment by brgavino** [comment]
@zhangtao1104 The files attached are x86 DLLs, would it be possible to share these compiled for x86_64 target, also?

**Comment by zhangtao1104** [comment]
In my opinion, x86 win exe can run in most of x64 win pc. 
We don't have x64 dll right now ,  but the next version of unity sdk we will support both of x86 and x64 plugin.

**Comment by sx1n90** [comment]
But x86 plugin not work in editor. In asset store new plugin version is 2.5.4(Aug 26, 2019) still not have any version for windows. Debug on device is pain in the ass. Taking into account not very detailed documentation for unity - its vary big pain.

**Comment by zhangtao1104** [comment]
@sx1n90  @brgavino @cosmo-naut   We have update the Unity sdk in the unity Asset store, we had develop many new good features. You can try to  download the Agora unity sdk from the Unity Asset Store, the plugin  can support all platfrom  (Android , IOS, Windows, Mac), it can also support Voice and Video , ar and vr.
